volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/wordpress

networks:
  dockernet:
    driver: bridge

services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: ".env"
    restart: on-failure
    networks:
      - dockernet
    volumes:
      - mariadb:/var/lib/mariadb

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file: ".env"
    restart: on-failure
    networks:
      - dockernet
    volumes:
      - wordpress:/usr/share/webapps/wordpress
    depends_on: # TODO: use long syntax for service_healthy
      - mariadb

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    env_file: ".env"
    restart: on-failure
    networks:
      - dockernet
    volumes:
      - wordpress:/usr/share/webapps/wordpress
    depends_on:
      - wordpress
    # the only exposed port in the whole thing
    # has to be quoted to avoid conflict with YAML base-60 format
    ports:
      - "443:443" 
